build-job:
  stage: build
  when: always
  tags:
    - aladales
  script:
    - cd src/part_2/C3_SimpleBashUtils-0/src/cat && make s21_cat && cd ../grep && make s21_grep
  artifacts:
    paths:
      - src/part_2/C3_SimpleBashUtils-0/src/cat
      - src/part_2/C3_SimpleBashUtils-0/src/grep
    expire_in: 30 days
  after_script:
    - echo "result=$CI_JOB_STATUS"
    - sh src/tg_bot/messages.sh
style_test:
  stage: test
  when: always
  tags:
    - aladales
  script:
    - cd src/part_2/C3_SimpleBashUtils-0/src/cat  && make check && cd ../grep && make check
  after_script:
    - echo "result=$CI_JOB_STATUS"
    - sh src/tg_bot/messages.sh
inter_test:
  stage: test
  when: always
  tags:
    - aladales
  script:
    - cd src/part_2/C3_SimpleBashUtils-0/src/cat && make s21_cat_test && cd ../grep && make s21_grep_test
  after_script:
    - echo "result=$CI_JOB_STATUS"
    - sh src/tg_bot/messages.sh
