stages:
  - build
  - style
  - test
  - deploy

builds:
  stage: build
  when: always
  tags:
    - aladales_test
  script:
    - cd src/C3_SimpleBashUtils-0/src/cat && make s21_cat && cd ../grep && make s21_grep
  artifacts:
    paths:
      - src/C3_SimpleBashUtils-0/src/cat
      - src/C3_SimpleBashUtils-0/src/grep
    expire_in: 30 days
  after_script:
    - echo "result=$CI_JOB_STATUS"
    - sh src/tg_bot/messages.sh

styles:
  stage: style
  when: always
  tags:
    - aladales_test
  script:
    - cd src/C3_SimpleBashUtils-0/src/cat  && make check && make clean && cd ../grep && make check && make clean
  after_script:
    - echo "result=$CI_JOB_STATUS"
    - sh src/tg_bot/messages.sh

tests:
  stage: test
  when: always
  tags:
    - aladales_test
  script:
    - cd src/C3_SimpleBashUtils-0/src/cat && make test && make clean && cd ../grep && make test && make clean
  after_script:
    - echo "result=$CI_JOB_STATUS"
    - sh src/tg_bot/messages.sh
deploys:
  stage: deploy
  when: manual
  tags:
    - aladales_test
  dependencies:
    - builds
  before_script:
    - eval $(ssh-agent -s)
  script:
    - cd src/helpers && sh ssh-copy.sh
  after_script:
    - echo "result=$CI_JOB_STATUS"
    - sh src/tg_bot/messages.sh
