build-job:
  stage: build
  when: always
  tags:
    - aladales_test
  script:
    - cd src/C3_SimpleBashUtils-0/src/cat && make s21_cat && cd ../grep && make s21_grep
  artifacts:
    paths:
      - src/C3_SimpleBashUtils-0/src/cat
      - src/C3_SimpleBashUtils-0/src/grep
    expire_in: 30 days
  after_script:
    - echo "result=$CI_JOB_STATUS"
    - sh src/tg_bot/messages.sh

style_test:
  stage: style_test
  when: always
  tags:
    - aladales_test
  script:
    - cd src/C3_SimpleBashUtils-0/src/cat  && make check && make clean && cd ../grep && make check && make clean
  after_script:
    - echo "result=$CI_JOB_STATUS"
    - sh src/tg_bot/messages.sh

inter_test:
  stage: inter_test
  when: always
  tags:
    - aladales_test
  script:
    - cd src/C3_SimpleBashUtils-0/src/cat && make test && make clean && cd ../grep && make test && make clean
  after_script:
    - echo "result=$CI_JOB_STATUS"
    - sh src/tg_bot/messages.sh
